version: "3.8"
services:
  api:
    build:
      context: api/docker/nginx
    ports:
      - "24891:80"
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm
  api-php-fpm:
    build:
      context: api/docker/php-fpm
    environment:
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
    volumes:
      - ./api:/app
  api-php-cli:
    build:
      context: api/docker/php-cli
    environment:
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
    volumes:
      - ./api:/app
  api-postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "24892:5432"
volumes:
  api-postgres:
